require:
  - standard
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  Exclude:
    - vendor/bundle/**/*
    - .github/**/*
    - pkg/**/*
    - sig/**/*

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/FilePath:
  Enabled: false
