name: Ruby

on:
  - push
  - pull_request

jobs:
  build:
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: ubuntu-22.04
    name: Ruby ${{ matrix.ruby }} (AR ${{ matrix.activerecord }})
    strategy:
      fail-fast: false
      matrix:
        include:
          # https://github.com/ruby/setup-ruby
          # - ruby: "head" # cannot test on head as sqlite-ruby requires `ruby < '3.4.dev'`
          #   activerecord: "8.0"
          - ruby: "3.3"
            activerecord: "8.0"
          - ruby: "3.1"
            activerecord: "7.2"
          - ruby: "2.7"
            activerecord: "6.1"
          - ruby: "2.6"
            activerecord: "5.2"
          - ruby: "jruby-9.4.9"
            activerecord: "6.1"
          - ruby: "truffleruby-24.1.1"
            activerecord: "8.0"

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.activerecord }}.gemfile
      CC_TEST_REPORTER_ID: 2b0dd65d1c078b0d9f6edc768751ab9f210decdace1eae9651603a6bccff96ca

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # https://github.com/ruby/setup-ruby
      - name: Set up Ruby ${{ matrix.ruby }} (AR ${{ matrix.activerecord }})
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install codespell
        if: startsWith(matrix.ruby, '3.3') && matrix.activerecord == '8.0'
        run: |
          python -m pip install --upgrade pip
          pip install codespell==2.3.0
      - name: Check spelling with codespell
        if: startsWith(matrix.ruby, '3.3') && matrix.activerecord == '8.0'
        run: codespell --skip="./sig,./doc,./coverage,./vendor" || exit 1

      # Check code standards only for latest MRI. It takes a lot of time for jruby or truffleruby
      - name: Check Code Standards
        if: startsWith(matrix.ruby, '3.3') && matrix.activerecord == '8.0'
        run: bundle exec rubocop

      - name: Run Tests
        run: bundle exec rspec

      - name: Markdown linter
        if: startsWith(matrix.ruby, '3.3') && matrix.activerecord == '8.0'
        run: bundle exec mdl README.md CHANGELOG.md RELEASE.md

      # https://github.com/paambaati/codeclimate-action
      - name: Publish code coverage to code-climate
        uses: paambaati/codeclimate-action@v9.0.0
        if: (github.event_name == 'push') && startsWith(matrix.ruby, '3.3')
